### PR TITLE
Preloading models for docker servers

### PR DESCRIPTION
**Pull request by dogversioning**

### CODE REVIEW

**Comment by angus-lherrou** [comment]
lgtm!

**Review by angus-lherrou — APPROVED** [review]

**Review by tmills — APPROVED** [review]

**Comment by angus-lherrou** [comment]
Hi @dogversioning -- in the future, please don't merge changes that affect the Python package files directly into `main`

**Comment by dogversioning** [comment]
@angus-lherrou  oh jeez, sorry about that - i thought i had made a mistake with my target, won't happen again

**Comment by angus-lherrou** [comment]
@dogversioning no worries, I could’ve been clearer that I had changed it

**Pull request merged**
