### PR TITLE
Add requirements for transform_prot

### PR DESCRIPTION
**Pull request by angus-lherrou**
Exclude scispacy and en-core-sci-sm on arm64 platforms as `nmslib` install is broken). Still pin spaCy version for compatibility.

### CODE REVIEW

**Comment by tmills** [comment]
Does the error mean this is still a work in progress?

**Comment by angus-lherrou** [comment]
Looks like a pretty gnarly dependency conflict for 3.7. I think I’ll just have to gate transform_prot behind Python >= 3.8. @etgld thoughts?

**Comment by etgld** [comment]
@angus-lherrou that works for me.  At some point I can try to find a general alternative that doesn't have this issue ( maybe something from generic spaCy or stanza )

**Comment by angus-lherrou** [comment]
@tmills at this point we're building up a list of caveats for Python 3.7. I think it may be worth considering whether we want to continue supporting it as the minimum python version.

**Comment by tmills** [comment]
Yeah, I guess it is eol'd as of June. I'm ok with dropping python 3.7.

**Pull request merged**
